//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardCard
    {
        public int Id { get; set; }
        public string CardHeader { get; set; }
        public string CardBody { get; set; }
        public int BoardId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Board Board { get; set; }
    }
}
